#!/usr/bin/env bash
# Regenerate src/music.js (base64 background music) from audio/assets/music/*.mp3.
# Inlines each track as a data URI so both the source build and the single-file
# dist play music with no external files / no fetch() (same pattern as build-art.sh).
set -euo pipefail
cd "$(dirname "$0")/.."
SRC=audio/assets/music

node -e '
const fs=require("fs"),path=require("path"),dir=process.argv[1];
const files=fs.readdirSync(dir).filter(f=>/\.mp3$/.test(f)).sort();
let out="// AUTO-GENERATED by tools/build-music.sh — base64 background music, keyed by filename stem.\nexport const MUSIC = {\n";
for(const f of files){
  const stem=f.replace(/\.mp3$/,"");
  const b64=fs.readFileSync(path.join(dir,f)).toString("base64");
  out+="  "+JSON.stringify(stem)+": "+JSON.stringify("data:audio/mpeg;base64,"+b64)+",\n";
}
out+="};\n";fs.writeFileSync("src/music.js",out);
console.log("wrote src/music.js");
' "$SRC"
