#!/usr/bin/env bash
# Regenerate src/art.js (base64 UI icons) from art/assets/ui/*.png.
# Downscales each asset to display resolution, then inlines as data URIs so
# BOTH the source build and the single-file dist show the art (no external files).
set -euo pipefail
cd "$(dirname "$0")/.."
SRC=art/assets/ui
OPT="$(mktemp -d)"
trap 'rm -rf "$OPT"' EXIT
target() { case "$1" in
  stat-*|face-*|arrow-*) echo 96;;
  step-*) echo 160;;
  mode-*) echo 512;;
  logo-blockville|menu-bg) echo 1024;;
  favicon-mark) echo 0;;
  btn-free-build|btn-lets-build) echo 256;;
  *) echo 128;; esac; }
for f in "$SRC"/*.png; do
  stem=$(basename "$f" .png); t=$(target "$stem"); [ "$t" = "0" ] && continue
  if [ "$stem" = "menu-bg" ]; then sips -s format jpeg -s formatOptions 82 -Z "$t" "$f" --out "$OPT/$stem.jpg" >/dev/null
  else sips -Z "$t" "$f" --out "$OPT/$stem.png" >/dev/null; fi
done
node -e '
const fs=require("fs"),path=require("path"),dir=process.argv[1];
const skip=new Set(["mode-card-frame"]);
const files=fs.readdirSync(dir).filter(f=>/\.(png|jpg)$/.test(f)).sort();
let out="// AUTO-GENERATED by tools/build-art.sh — base64 UI art, keyed by filename stem.\nexport const ART = {\n";
for(const f of files){const stem=f.replace(/\.(png|jpg)$/,"");if(skip.has(stem))continue;
  const b64=fs.readFileSync(path.join(dir,f)).toString("base64");
  const mime=f.endsWith(".jpg")?"image/jpeg":"image/png";
  out+="  "+JSON.stringify(stem)+": "+JSON.stringify("data:"+mime+";base64,"+b64)+",\n";}
out+="};\n";fs.writeFileSync("src/art.js",out);
console.log("wrote src/art.js");
' "$OPT"
